name: Command-Line Tool
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - uses: actions/checkout@v2
      - name: test build-Build and run dev container task
        uses: devcontainers/ci@v0.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
      - name: Format
        run: |
          make format
      - name: Linting
        run: |
          make lint
      - name: Testing
        run: |
          make test
      - name: Deploy
        run: |
          make deploy